site_name: Træfik
site_description: Træfik Documentation
site_author: containo.us
site_url: https://docs.traefik.io

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/traefik'

# Documentation and theme
docs_dir: 'docs'
theme: united
# theme: readthedocs
# theme: 'material'
# theme: bootstrap

site_favicon: 'img/traefik.icon.png'

# Copyright
copyright: "Copyright &copy; 2016-2017 Containous SAS"

# Options
extra:
#   version: 0.2.2
  logo: img/traefik.logo.png
  # author:
  #   twitter: traefikproxy
  palette:
    primary: 'blue'
    accent: 'light blue'
  i18n:
    prev: 'Previous'
    next: 'Next'  
  
markdown_extensions:
#   - codehilite(css_class=code)
  - admonition
#   - toc:
#       permalink: '##'
  # - fenced_code
      
extra_css:
    - css/traefik.css
      
# Page tree
pages:
  - Getting Started: index.md
  - Basics: basics.md
  - Configration:
    - 'traefik.toml': 'configuration/toml.md'
    - 'Let''s Encrypt': 'configuration/acme.md'
  - Backends:
    - 'API backend': 'backends/api.md'
    - 'BoltDB backend': 'backends/boltdb.md'
    - 'Consul backend': 'backends/consul.md'
    - 'Docker backend': 'backends/docker.md'
    - 'DynamoDB backend': 'backends/dynamodb.md'
    - 'ECS backend': 'backends/ecs.md'
    - 'Etcd backend': 'backends/etcd.md'
    - 'Eureka backend': 'backends/eureka.md'
    - 'File backend': 'backends/file.md'
    - 'Kubernetes Ingress backend': 'backends/kubernetes.md'
    - 'Marathon backend': 'backends/marathon.md'
    - 'Rancher backend': 'backends/rancher.md'
    - 'Zookeeper backend': 'backends/zookeeper.md'
  - User Guide:
      - 'Configuration examples': 'user-guide/examples.md'
      - 'Swarm cluster': 'user-guide/swarm.md'
      - 'Swarm mode cluster': 'user-guide/swarm-mode.md'
      - 'Kubernetes': 'user-guide/kubernetes.md'
      - 'Marathon': 'user-guide/marathon.md'
      - 'Key-value store configuration': 'user-guide/kv-config.md'
      - 'Clustering/HA': 'user-guide/cluster.md'
      - 'Getting started with Docker & Lets Encrypt': 'user-guide/getting-started-with-docker-and-lets-encrypt.md'
  - Benchmarks: benchmarks.md
