logLevel = "DEBUG"

[entrypoints]
  [entrypoints.web]
  address = ":80"
    [entrypoints.web.redirect]
    entryPoint = "https"
  [entrypoints.web-secure]
  address = ":443"
    [entrypoints.web-secure.tls]

[acme]
email = "test@traefik.io"
storage = "/etc/traefik/conf/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
caServer = "http://traefik.boulder.com:4001/directory"
  [acme.httpChallenge]
  entryPoint="http"

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.localhost.com"
watch = true
exposedByDefault = false


