apiVersion: v1
kind: ReplicationController
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: containous/traefik:k8s
        name: traefik-ingress-lb
        imagePullPolicy: Always
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 10249
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - --kubernetes
        - --logLevel=DEBUG